name: Train Model on Push to Main

on:
  push:
    branches:
      - main

jobs:
  experiment:
    name: Experiment Job (Dev)
    runs-on: ubuntu-latest
    environment: dev  # 🔧 Link to your "dev" environment where AZURE_CREDENTIALS is stored

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Azure CLI and ML extension
        run: |
          az extension add -n ml -y
          az config set extension.use_dynamic_install=yes_without_prompt

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Submit dev job
        id: submit-dev
        run: |
          JOB_INFO=$(az ml job create \
            --file src/job.yml \
            --input training_data=azureml:diabetes-dev-folder@latest \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }} \
            --query "{name:name}" -o json)
          echo "job_name=$(echo $JOB_INFO | jq -r .name)" >> $GITHUB_OUTPUT

      - name: Wait for dev job to complete
        run: |
          STATUS="Queued"
          while [[ "$STATUS" == "Queued" || "$STATUS" == "NotStarted" || "$STATUS" == "Running" || "$STATUS" == "Finalizing" ]]; do
            sleep 20
            STATUS=$(az ml job show \
              --name ${{ steps.submit-dev.outputs.job_name }} \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }} \
              --query "status" -o tsv)
            echo "Current status: $STATUS"
          done
          if [[ "$STATUS" != "Completed" ]]; then
            echo "Experiment job failed with status: $STATUS"
            exit 1
          fi

  production:
    name: Production Job
    runs-on: ubuntu-latest
    needs: experiment
    environment: production  # 🔧 Link to your "production" environment where AZURE_CREDENTIALS is stored

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Azure CLI and ML extension
        run: |
          az extension add -n ml -y
          az config set extension.use_dynamic_install=yes_without_prompt

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Submit prod job
        run: |
          az ml job create \
            --file src/job.yml \
            --input inputs.training_data=azureml:diabetes-prod-folder@latest \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }}

      - name: Wait for prod job to complete
        run: |
          STATUS="Queued"
          while [[ "$STATUS" == "Queued" || "$STATUS" == "NotStarted" || "$STATUS" == "Running" || "$STATUS" == "Finalizing" ]]; do
            sleep 20
            STATUS=$(az ml job show \
              --name ${{ steps.submit-prod.outputs.job_name }} \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }} \
              --query "status" -o tsv)
            echo "Current status: $STATUS"
          done
          if [[ "$STATUS" != "Completed" ]]; then
            echo "Production job failed with status: $STATUS"
            exit 1
          fi